---
testingRegion: "us-west-2"
s3ReleaseCandidateBucketName: "aws-otel-collector-release-candidate"
s3BucketName: "aws-otel-collector-test"
sshKeyS3BucketName: "aoc-ssh-key"
traceDataS3BucketName: "trace-expected-data"  
testingImageRepoName: "611364707713.dkr.ecr.us-west-2.amazonaws.com/aws/aws-otel-collector"
