---
testingRegion: "us-west-2"
s3ReleaseCandidateBucketName: "aoc-otel-collector-release-candidate-release"
s3BucketName: "aws-otel-collector"
sshKeyS3BucketName: "aoc-ssh-key"
traceDataS3BucketName: "trace-expected-data"  
testingImageRepoName: "020628701572.dkr.ecr.us-west-2.amazonaws.com/aws-observability/aws-otel-collector"
