---
testingRegion: "us-west-2"
s3ReleaseCandidateBucketName: "aoc-release-candidate-release"
s3BucketName: "aws-observability-collector-release"
sshKeyS3BucketName: "aoc-ssh-key-release"
traceDataS3BucketName: "trace-expected-data-release"  
testingImageRepoName: "ghcr.io/aws-observability/aws-observability-collector"
