changed:
  - '.github/workflows/PR-build.yml'
  - 'cmd/**'
  - 'config/**'
  - 'deployment-template/**'
  - 'e2etest/**'
  - 'pkg/**'
  - 'tools/**'
  - 'testbed/**'
  - 'Makefile'
  - 'go.sum'
  - '.patches/**'
  - 'vendor/**'
all:
  - '**'
version:
  - 'VERSION'
