# Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

name: public-ecr-image-push

on:        
  workflow_dispatch:
    inputs:
      version:
        description: 'the image version to push'
        required: true
      ecrRepo:
        description: 'the name of the image to push'
        required: true
      githubRepo:
        description: 'the name of the org and repository where code is hosted'
        required: true
      pathToDockerfile:
        description: 'the path within the repository to the folder containing the dockerfile'
        default: "."
  
env:
  ECR_REPO: aws-observability/${{ github.event.inputs.ecrRepo }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.RELEASE_${{ecrRepo}}_KEY_ID }}
          aws-secret-access-key: ${{ secrets.RELEASE_${{ecrRepo}}_SECRET }}
          aws-region: us-west-2    
      
      - name: Clone Image Code Repo
        uses: actions/checkout@master
        with:
          name: ${{ github.event.inputs.githubRepo }}
        
      - name: Build Image
        run: |
          docker build ${{ github.events.inputs.githubRepo }}/${{ github.events.inputs.pathToDockerfile}} -t ${{ github.event.inputs.ecrRepo }}
      
      - name: upload to ECR
        run: |
          aws ecr-public get-login-password --region us-west-2 | docker login --username AWS --password-stdin public.ecr.aws/aws-observability
          docker tag ${{ github.event.inputs.ecrRepo }} public.ecr.aws/$ECR_REPO:${{ github.event.inputs.version }}
          docker tag ${{ github.event.inputs.ecrRepo }} public.ecr.aws/$ECR_REPO:latest 
          docker push public.ecr.aws/$ECR_REPO:${{ github.event.inputs.version }}
          docker push public.ecr.aws/$ECR_REPO:latest    