# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

name: Mirror ADOT Operator

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'the desired version number of the operator (ex. v0.45.0)'
        required: true

jobs:           
  release-latest-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ~1.18.9

      - name: Login to Public Release ECR
        uses: docker/login-action@v2
        with:
          registry: public.ecr.aws
          username: ${{ secrets.RELEASE_KEY_ID }}
          password: ${{ secrets.RELEASE_SECRET }}
        env:
          AWS_REGION: us-east-1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.RELEASE_KEY_ID }}
          aws-secret-access-key: ${{ secrets.RELEASE_SECRET }}
          aws-region: us-west-2

      - name: Version checking
        id: version
        run: VERSION="${{ github.event.inputs.version }}" bash tools/release/adot-operator-images-mirror/version-check.sh

      - name: Mirror ADOT operator
        if: ${{ steps.version.outputs.update-operator == 'true' }}
        run: cd tools/release/adot-operator-images-mirror && go run ./
        env:
          AWS_SDK_LOAD_CONFIG: true
