# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

name: Hourly Resources Cleaner

on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:

jobs:
  clean-soaking-resources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.INTEG_TEST_AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.INTEG_TEST_AWS_KEY_SECRET }}
          aws-region: us-west-2
          
      - name: Set up terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Clean resources which are created before yesterday
        id: clean-resources
        run: sh tools/workflow/clean-terraform-resources.sh

      - name: Re-upload terraform state on failure
        if: ${{ failure() || cancelled() }}
        run: |
          key_name="${{ steps.clean-resources.outputs.key-name }}"
          package="downloaded_terraform/$key_name"
          if [[ -f $package ]]; then
            aws s3 cp $package s3://soaking-terraform-state/$key_name
          fi