# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

name: Resources Cleaner

on:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  clean-soaking-resources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.INTEG_TEST_AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.INTEG_TEST_AWS_KEY_SECRET }}
          aws-region: us-west-2
          
      - name: Set up terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Clean resources which are created before yesterday
        run: sh tools/workflow/clean-terraform-resources.sh

      - name: Clean distributor documents
        run: go run e2etest/clean/clean_distributor.go
        env:
          AWS_SDK_LOAD_CONFIG: true
